### ISSUE TITLE
SPane error on scroll

### ISSUE THREAD

**Issue by ochagnon** [StratifyLabs/StratifyQML#19]
I need to wrap some content into something that scroll, I'm trying `SPane` with:

```
import QtQuick.Controls 1.2

import "StratifyQML"

ApplicationWindow {
    id: app
    visible: true
    property string appTitle: "Test"

    minimumWidth: 500
    minimumHeight: 200

    SCustomize {
        id: theme
        gray_base: "#303F9F"
    }

    SPane {
        data: SColumn {
            SRow {
                SBaseRectangleText {
                    text: "Row 1"
                }
            }
            SRow {
                SBaseRectangleText {
                    text: "Row 2"
                }
            }
            SRow {
                SBaseRectangleText {
                    text: "Row 3"
                }
            }
            SRow {
                SBaseRectangleText {
                    text: "Row 4"
                }
            }
            SRow {
                SBaseRectangleText {
                    text: "Row 5"
                }
            }
            SRow {
                SBaseRectangleText {
                    text: "Row 6"
                }
            }
            SRow {
                SBaseRectangleText {
                    text: "Row 7"
                }
            }
        }
    }
}
```

When I load that QML:

```
qrc:/qml/StratifyQML/SPane.qml:27:5: QML Flickable: Binding loop detected for property "contentHeight"
```

loop in console a few hundred times and:

```
qrc:/qml/main.qml:18:5: QML SPane: Binding loop detected for property "implicitHeight"
```

**Comment by tyler-gilbert** [comment]
I see the problem. It is in SPane

        implicitHeight: fillHeight ? ((parent != null) ? parent.height : 0) : contents.childrenRect.height + paddingVertical*2;

if you add:

    style: "fill"

to SPane that will set the fillHeight variable to true and the SPane should take the height of the parent.

Alternatively, you can just override the implicitHeight value with a fixed variable like

    implicitHeight: 200

You can play around with setting height and implicitHeight.

I will add this as a bug so that it is clear SPane needs to be the size of the parent or a fixed size.

**Comment by bclermont** [comment]
@tyler-gilbert these kinds of details aren't documented in `.md` or in source code as comment in file such as `SPane.qml`

If I wish to give back "documentation" on the usage, like this case, where it should be? comment or `.md`?

**Comment by tyler-gilbert** [comment]
@bclermont I would say let's put it in the qml file.  Eventually, I would like to have the doc's generated using http://doc.qt.io/qt-5/qdoc-categories.html
