### ISSUE TITLE
Automatic Row Height

### ISSUE THREAD

**Issue by ochagnon** [StratifyLabs/StratifyQML#20]
As there is no doc and the examples don't show what I'm trying to achieve, I'm trying with an issue.

I'm trying to have content that automatically resize like the following example.

![example](https://cloud.githubusercontent.com/assets/1025638/21971366/f08f4d7e-dbea-11e6-9425-2e44fd670266.jpg)

The red rows height is their content size. But I wish to have one row resize based on the window size.
This is a common case.

Sadly, it seem that I can't apply the same logic as for web-bootstrap here.

**Comment by tyler-gilbert** [comment]
In the SColumn and SRow add

    style: "fill";

see [STest.qml](https://github.com/StratifyLabs/StratifyQML/blob/master/StratifyLabs/UI/STest.qml) which has an example (of sorts).

**Comment by ochagnon** [comment]
Thank you it work now
