### ISSUE TITLE
Doc QML Project can't be executed

### ISSUE THREAD

**Issue by ochagnon** [StratifyLabs/StratifyQML#24]
First, thank you for this great upgrade! I'm looking forward to use the new version!

I'm trying to follow your doc and I open https://github.com/StratifyLabs/StratifyQML/commits/master/StratifyLabs/Doc/StratifyLabs-UI-Doc.qmlproject in QT Creator and get this:

<img width="931" alt="screen shot 2017-03-08 at 17 04 23" src="https://cloud.githubusercontent.com/assets/1025638/23697108/694d2e62-0421-11e7-9617-9915fcbed1c1.png">

I also tried to add `StratifyLabs` to my project, manually. and it can't find there either.
Is there a problem in `qmldir`? or any other files?

**Comment by tyler-gilbert** [comment]
The qmlproject is broken in that respect. I wasn't quite able to figure out how to make it reference the relative folder but it can be done.

There are two workarounds:
- Open the UI project and add "install" to the "Release" builds make file arguments build the project then try again to run the Doc app
- Download the SL.UI documentation app from the [releases section](https://github.com/StratifyLabs/StratifyQML/releases)

![image](https://cloud.githubusercontent.com/assets/6136781/23713571/9de526fe-03e3-11e7-85e8-af3154d7aea2.png)

**Comment by ochagnon** [comment]
Ah, ok thanks. but I was more looking to use `UI.2` in my own project. Which seem to suffer from the same problem

**Comment by ochagnon** [comment]
> Ah, ok thanks. but I was more looking to use UI.2 in my own project. Which seem to suffer from the same problem

#27 for this
