### ISSUE TITLE
SAnimator must be inside a layout (SColumn or SRow)

### ISSUE THREAD

**Issue by tyler-gilbert** [StratifyLabs/StratifyQML#25]
The SAnimator object won't size correctly without being inside a layout object.

**Comment by knro** [comment]
I just tested "Doc" and nothing inside would resize to the window size. Is this the same bug?
![spectacle fv9552](https://cloud.githubusercontent.com/assets/5986347/24331626/d5bc5280-1240-11e7-97ad-6d7cde4666ad.png)

**Comment by tyler-gilbert** [comment]
@knro 

This is due to the same issue. I had written a workaround but hadn't committed it yet.  It has been committed now.

**Comment by knro** [comment]
Yes thanks that fixed it!!! Thanks for the great project!
