### ISSUE TITLE
Missing SItem in 2.0

### ISSUE THREAD

**Issue by bclermont** [StratifyLabs/StratifyQML#29]
https://github.com/StratifyLabs/StratifyQML/blob/master/StratifyLabs/UI/UI.2/SLoader.qml#L20

but not in https://github.com/StratifyLabs/StratifyQML/tree/master/StratifyLabs/UI/UI.2

```
./SNavbar.qml:    property var item: SItem {
./SCarousel.qml:SItem {
./SPopover.qml:SItem {
./SBreadcrumb.qml:SItem {
```

**Comment by bclermont** [comment]
4 files still refers to it

**Comment by tyler-gilbert** [comment]
Good catch. Those 4 files are not implemented in 2.0. I am going to make them QML Item{} objects with no function until a later 2.1 or later release.

**Comment by tyler-gilbert** [comment]
The 2.0 references were also removed from the qmldir file.

**Comment by bclermont** [comment]
You forgot `SLoader` too

**Comment by tyler-gilbert** [comment]
OK. I just gave SLoader the same treatment.
