### ISSUE TITLE
Warning when clicking beyond data in a table

### ISSUE THREAD

**Issue by tyler-gilbert** [StratifyLabs/StratifyQML#32]
When a table has extra rows, clicking on the extra blank rows generates a warning:

    Warning: file:///Users/tgil/Qt-5.8/5.8/clang_64/qml/StratifyLabs/UI/UI.2/STablePrivate.qml:168: Error: Cannot assign [undefined] to int

**Comment by knro** [comment]
Table view is completely garbled when trying out the latest Doc from Github
![spectacle tj9731](https://cloud.githubusercontent.com/assets/5986347/24331657/978a91b0-1241-11e7-998b-a8c7ae2733b9.png)
