### ISSUE TITLE
SPanel: display corruption using Repeater/SList

### ISSUE THREAD

**Issue by bclermont** [StratifyLabs/StratifyQML#40]
It seem we can't use `SPanel` with dynamically data:

SPanel widget: https://github.com/bclermont/stratifyqml-issue-40/blob/a9acd5196437853215b2f217ec1f6458fd5dc4aa/XXXItem.qml

I'm trying to create multiple instance `SPanel` through a `Repeater` or a `SList` and it just show completely broken.

But the thing is it look nice if I initialize it at startup like:

https://github.com/bclermont/stratifyqml-issue-40/blob/master/main-ok-static.qml#L30

or

https://github.com/bclermont/stratifyqml-issue-40/blob/master/main-ok-model-inline.qml#L32

![screenshot from 2017-12-01 15-42-10](https://user-images.githubusercontent.com/474302/33472763-9d506520-d6ae-11e7-9db6-ec8449df0fc5.png)

If I do it that way:

https://github.com/bclermont/stratifyqml-issue-40/blob/master/main-notok.qml#L36

it's broken:

![screenshot from 2017-12-01 15-42-12](https://user-images.githubusercontent.com/474302/33472772-a575db0e-d6ae-11e7-9348-b5038cf4d17a.png)

All code to reproduce the problem is at https://github.com/bclermont/stratifyqml-issue-40

**Comment by arknable** [comment]
I can get correct result by wrapping `XXXItem.qml` in a `Component` and add the childrens to `SRow` manually, then call `SRow`'s `alignChildren()` function. screenshot attached.

![screen shot 2017-12-01 at 15 41 04](https://user-images.githubusercontent.com/13412168/33474776-8a68a846-d6ae-11e7-96ac-73040dcd4b1f.png)

**Comment by arknable** [comment]
here's my `main.qml` source code

```
import QtQuick 2.7
import QtQuick.Controls 2.0
import QtQuick.Window 2.2
import StratifyLabs.UI 2.0

ApplicationWindow {
    visible: true
    width: 640
    height: 480
    visibility: "Maximized"


    SContainer {
        SColumn {
            SRow {
                SText {
                    attr.blockWidth: Text.Wrap
                    text: "Repeater with SPanel don't have a model yet, click to set it"
                }
            }

            SRow {
                SButton {
                    id: btn
                    text: "Click me to load model"
                    onClicked: {
                        btn.visible = false                        
                        var model = ["abc", "def", "ghi"]
                        var items = []
                        for(var i = 0; i < model.length; i++) {
                            items.push(itemComponent.createObject(row, { path: model[i] }))
                        }
                        row.children = items
                        row.alignChildren()
                    }
                }
            }

            SRow {
                id: row
            }
        }
    }

    Component {
        id: itemComponent
        XXXItem {}
    }
}

```

**Comment by arknable** [comment]
previously I tried something like this but didn't work. swapping call between `alignChildren()` and `adjustWidth()` also didn't work. I see in `SRow`'s source code the author is using those functions to layout the childrens so probably it's a bug on those functions ? .... I'm not sure.

```
SContainer {
        SColumn {
            SRow {
                SText {
                    attr.blockWidth: Text.Wrap
                    text: "Repeater with SPanel don't have a model yet, click to set it"
                }
            }

            SRow {
                SButton {
                    id: btn
                    text: "Click me to load model"
                    onClicked: {
                        btn.visible = false
                        resultList.model = ["abc", "def", "ghi"]
                        row.alignChildren()
                        row.adjustWidth()
                    }
                }
            }
            
            SRow {
                id: row
                Repeater {
                    id: resultList
                 
                    XXXItem {
                        path: modelData
                    }
                }
            }
        }
    }
```

**Comment by bclermont** [comment]
@arknable thank you!

@tyler-gilbert you see the problem?

**Comment by tyler-gilbert** [comment]
@bclermont I am taking a look. I will let you know if I can figure something out.

**Comment by tyler-gilbert** [comment]
@bclermont @arknable 

Here is the problem.  SRow uses `children.length` to calculate the widths. However, the "Repeater" item is showing up in the count but shouldn't be used in the calcs. So children.length ends up being 4 instead of 3. This is why @arknable second code example doesn't work.

The method above where items are added directly to SRow works because children.length is the same as the visible children.

In order to support Repeater, we would need to create an SRepeater object that would tell SRow and SColumn not to count it among children.length. Or is there something SRow can look at to see that Repeater isn't a display item?

Adding

````
  onChildrenChanged: {
    alignChildren();
    adjustWidth();
  }
````

to SRow prevents the need from calling alignChildren(), but it won't get rid of the extra Repeater child.

So, is creating SRepeater the preferred solution or is there some way children.length can be limited to displayable items rather than all items?

**Comment by tyler-gilbert** [comment]
@bclermont 

The other option would be to just add a function to SRow that would add the items in a model basically turning

````
                        var model = ["abc", "def", "ghi"]
                        var items = []
                        for(var i = 0; i < model.length; i++) {
                            items.push(itemComponent.createObject(row, { path: model[i] }))
                        }
                        row.children = items
                        row.alignChildren()
````
to
````
var model = ["abc", "def", "ghi"];
row.repeater(model);
````

**Comment by bclermont** [comment]
I have a strong feeling that a `SRepeater` new type should be added.
it's more consistent with the rest of StratifyQML... there is various types/widgets and we don't need to use method to achieve basic placements.
the API of a new type is like just using `Repeater`, which is simple

**Comment by tyler-gilbert** [comment]
@bclermont That sounds good to me. I will add an SRepeater item.

**Comment by bclermont** [comment]
but there is one other thing... we have the same problem with `SList`, I feel the problem will be different, right?

**Comment by tyler-gilbert** [comment]
@bclermont Can you open a new issue for SList and put up some example code to re-create the problem?

**Comment by arknable** [comment]
@tyler-gilbert I created the issue here: https://github.com/StratifyLabs/StratifyQML/issues/41
