### ISSUE TITLE
Display corruption using SList

### ISSUE THREAD

**Issue by arknable** [StratifyLabs/StratifyQML#41]
This is probably related to this issue: https://github.com/StratifyLabs/StratifyQML/issues/40. So basically same case but using `SList` instead of `SRepeater`. I put a reproducible sample on following repository: https://github.com/arknable/stratify_list_issue.

**Comment by bclermont** [comment]
@tyler-gilbert is this fixed in v3?

**Comment by tyler-gilbert** [comment]
@bclermont v3 is for Qt 5.10 and isn't ready for production.

I will see if I can fix it in 2.x
